### ISSUE TITLE
好帅

### ISSUE THREAD

**Issue by maiqingqiang** [yiranzai/yiranzai.github.io#1]
* [ ] I agree to follow the [Code of Conduct](https://github.com/jgraph/drawio/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by yiranzai** [comment]
别人的东西，就是把那个draw.io 搞到自己仓库了

**Comment by maiqingqiang** [comment]
好卡  加载半天

**Comment by yiranzai** [comment]
是啊，可以考虑下docker部署到国内
或者直接下载desktop本地离线使用就行了
